FROM ubuntu:22.04
RUN apt-get clean
RUN apt-get update
RUN apt-get install --yes --no-install-recommends apt-transport-https ca-certificates software-properties-common curl wget build-essential python3 python3-dev python3-pip gnupg-agent supervisor vim
RUN curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -
RUN add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu  $(lsb_release -cs) \ stable"
RUN apt-get update
RUN apt-get install -y docker-ce docker-ce-cli containerd.io

#jdk repository
RUN add-apt-repository ppa:openjdk-r/ppa

RUN apt-get update

RUN apt-get install --yes --no-install-recommends openjdk-8-jdk
RUN update-alternatives --config java
RUN update-alternatives --config javac

RUN apt-get install --yes --no-install-recommends maven

# other stuff needed by the builder scripts
RUN pip3 install --upgrade six>=1.10
RUN pip3 install setuptools awscli requests logger boto3


RUN pip install requests logger

COPY zbuild.sh /zbuild.sh
COPY zbuildmonitor.py /zbuildmonitor.py

# set up supervisord
ADD supervisord.conf /etc/supervisor/conf.d/supervisord.conf
ENTRYPOINT ["/bin/bash", "-c", "/usr/bin/supervisord -c /etc/supervisor/conf.d/supervisord.conf -n"]